workflows:
  ios-app:
    name: Drop2Life iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          chmod +x ./node_modules/.bin/cap
          npx cap sync ios
      - name: Build iOS app
        script: |
          xcodebuild -project App.xcodeproj \
                     -scheme App \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath $HOME/build.xcarchive
          xcodebuild -exportArchive \
                     -archivePath $HOME/build.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $HOME/build
    artifacts:
      - build/*.ipa
