workflows:
  ios-app:
    name: Build iOS App
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
    scripts:
      - npm install
      - chmod +x ./node_modules/.bin/cap
      - npx cap sync ios
      - cd ios
      - xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release archive -archivePath $HOME/build.xcarchive
      - xcodebuild -exportArchive -archivePath $HOME/build.xcarchive -exportOptionsPlist ../exportOptions.plist -exportPath $HOME/build
    artifacts:
      - build/**.ipa
